name: Contribution Snake

on:
  schedule:
    - cron: "0 */12 * * *"   # run every 12 hours
  workflow_dispatch:          # run manually from Actions tab

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate snake SVG
        uses: Platane/snk@master
        with:
          github_user_name: artemdev9
          outputs: dist/github-contribution-grid-snake.svg

      - name: Publish to output branch
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
